Repository vrchatapi/specification, pull requests merged in 2021-08, with the labels that each got.

#28 feature(worlds): add worlds api
  openapi.yaml
  openapi/components/responses/CreateWorldNotAllowedYetError.yaml
  openapi/components/responses/SeeOtherUserFavoritesError.yaml
  openapi/components/responses/SeeOtherUserRecentsError.yaml
  openapi/components/responses/WorldNotFoundError.yaml
  openapi/components/schemas/CurrentUser.yaml
  openapi/components/schemas/LimitedUnityPackage.yaml
  openapi/components/schemas/LimitedUser.yaml
  openapi/components/schemas/LimitedWorld.yaml
  openapi/components/schemas/MIMEType.yaml
  openapi/components/schemas/Platform.yaml
  openapi/components/schemas/UnityPackage.yaml
  openapi/components/schemas/UnityPackageID.yaml
  openapi/components/schemas/User.yaml
  openapi/components/schemas/World.yaml
Labels: Type: Enhancement, Priority: High, Status: Completed

#29 Clarify Tag prefixes further
  openapi/components/schemas/Tag.yaml
Labels: Type: Enhancement, Priority: Low

#31 feature(avatars): add avatars api
  openapi/components/responses/AvatarNotFoundError.yaml
  openapi/components/responses/FeaturedSetNotAdminError.yaml
  openapi/components/responses/MissingCredentialsError.yaml
  openapi/components/schemas/Avatar.yaml
  openapi/components/schemas/UnityPackage.yaml
  openapi/openapi.yaml
Labels: Type: Enhancement, Priority: High, Status: Review Needed

#34 feature(playermoderation): add playermoderation api
  .github/redocly-plugins/remove-internal.js
  openapi/components/responses/OkSuccess.yaml
  openapi/components/responses/PlayerModerationDeleteOthersError.yaml
  openapi/components/responses/PlayerModerationNotFoundError.yaml
  openapi/components/responses/PlayerModerationRemovedSuccess.yaml
  openapi/components/responses/PlayerModerationUnmoderatedSuccess.yaml
  openapi/components/schemas/PlayerModeration.yaml
  openapi/components/schemas/PlayerModerationID.yaml
  openapi/components/schemas/PlayerModerationType.yaml
  openapi/openapi.yaml
Labels: Type: Enhancement, Priority: High, Status: Completed

#36 Setup Release Action flow
  .github/workflows/ci.yaml
Labels: Type: Maintenance

#50 fix(favorite): type is not read-only, it is submitted during addFavorite
  openapi/components/schemas/FavoriteType.yaml
Labels: Type: Bug, Priority: High

#51 @Foorack fix(auth): pastDisplayNames is an object array, not string array
  openapi/components/schemas/CurrentUser.yaml
  openapi/components/schemas/PastDisplayName.yaml
Labels: Type: Bug, Priority: High
