Repository vrchatapi/specification, pull requests merged in 2021-07, with the labels that each got.

#2 Clean up operation ID's
  openapi.yaml
Labels: enhancement

#4 Add Notification endpoints
  openapi.yaml
  openapi/components/schemas/CurrentUser.yaml
  openapi/components/schemas/Error.yaml
  openapi/components/schemas/LimitedUser.yaml
  openapi/components/schemas/Notification.yaml
  openapi/components/schemas/NotificationDetailInvite.yaml
  openapi/components/schemas/NotificationID.yaml
  openapi/components/schemas/Response.yaml
  openapi/components/schemas/Success.yaml
  openapi/components/schemas/Tag.yaml
  openapi/components/schemas/User.yaml
  openapi/components/schemas/UserID.yaml
Labels: Priority: Medium, Type: Enhancement, Type: Maintenance

#15 Added offline parameter to /auth/user/friends
  openapi.yaml
Labels: Priority: Medium, Status: Accepted, Type: Enhancement

#14 Made ConfigDynamicWorldRows.tag nullable
  openapi/components/schemas/Config.yaml
Labels: Priority: High, Status: Completed, Type: Bug

#16 Added location to LimitedUser
  openapi/components/schemas/LimitedUser.yaml
Labels: Priority: Medium, Type: Enhancement

#17 Re-license under MIT
  LICENSE
  openapi.yaml
Labels: Priority: Medium, Status: Review Needed, Type: Maintenance

#18 Run OpenAPI Bundler as GitHub CI task
  .github/workflows/ci.yaml
Labels: Priority: Low, Status: Review Needed, Type: Maintenance

#13 Add FileAPI endpoints
  openapi.yaml
  openapi/components/schemas/AvatarID.yaml
  openapi/components/schemas/Config.yaml
  openapi/components/schemas/File.yaml
  openapi/components/schemas/FileData.yaml
  openapi/components/schemas/FileID.yaml
  openapi/components/schemas/FileStatus.yaml
  openapi/components/schemas/FileVersion.yaml
  openapi/components/schemas/MIMEType.yaml
  openapi/components/schemas/Tag.yaml
Labels: Priority: High, Status: Completed, Type: Enhancement

#21 Auth endpoints only require basic auth
  openapi.yaml
Labels: Priority: Medium, Status: Completed, Type: Bug

#22 Add CI linting check
  .github/workflows/ci.yaml
  .gitignore
  .spectral.yaml
  openapi.yaml
  openapi/components/schemas/Config.yaml
  openapi/components/schemas/MIMEType.yaml
  package-lock.json
  package.json
Labels: Priority: Low, Status: Completed, Type: Maintenance

#23 Document Set-Cookie and 2FA rememberance cookie
  openapi.yaml
Labels: Priority: Medium, Type: Enhancement

#24 Remove redundant wrappers around Date and DateTime
  openapi.yaml
  openapi/components/schemas/CurrentUser.yaml
  openapi/components/schemas/Date.yaml
  openapi/components/schemas/DateTime.yaml
  openapi/components/schemas/FileVersion.yaml
  openapi/components/schemas/Notification.yaml
  openapi/components/schemas/User.yaml
Labels: Priority: Medium, Status: Completed, Type: Maintenance

#25 Feature/worlds
  openapi.yaml
  openapi/components/schemas/LimitedWorld.yaml
  openapi/components/schemas/ReleaseStatus.yaml
Labels: Priority: High, Status: Completed, Type: Enhancement

#26 These user fields are nullable
  openapi/components/schemas/User.yaml
Labels: Priority: Low, Status: Completed, Type: Bug
