Repository vrchatapi/specification, pull requests merged in 2021-11, with the labels that each got.

#114 feature: add avatarImageUrl description
  openapi/components/schemas/CurrentAvatarImageUrl.yaml
  openapi/components/schemas/CurrentAvatarThumbnailImageUrl.yaml
  openapi/components/schemas/CurrentUser.yaml
  openapi/components/schemas/LimitedUser.yaml
  openapi/components/schemas/User.yaml
Labels: Type: Enhancement, Priority: High

#116 feature: add IPS endpoint
  openapi/components/parameters.yaml
  openapi/components/paths.yaml
  openapi/components/paths/system.yaml
  openapi/components/responses/system/InfoPushListResponse.yaml
  openapi/components/schemas/APIConfig.yaml
  openapi/components/schemas/DynamicContentRow.yaml
  openapi/components/schemas/InfoPush.yaml
  openapi/components/schemas/InfoPushData.yaml
  openapi/components/schemas/InfoPushDataClickable.yaml
  openapi/components/schemas/ReleaseStatus.yaml
Labels: Priority: Medium, Type: Undocumented Endpoint

#118 docs: flush out User and Avatar documentation
  openapi/components/requests/CreateAvatarRequest.yaml
  openapi/components/requests/CreateFileRequest.yaml
  openapi/components/requests/CreateWorldRequest.yaml
  openapi/components/requests/UpdateAvatarRequest.yaml
  openapi/components/requests/UpdateUserRequest.yaml
  openapi/components/requests/UpdateWorldRequest.yaml
  openapi/components/schemas/Avatar.yaml
  openapi/components/schemas/DeploymentGroup.yaml
  openapi/components/schemas/FileData.yaml
  openapi/components/schemas/InstanceID.yaml
  openapi/components/schemas/User.yaml
  openapi/components/schemas/UserID.yaml
  openapi/components/schemas/WorldID.yaml
Labels: Type: Enhancement, Priority: Medium

#119 fix: add missing Region type "unknown"
  openapi/components/schemas/Region.yaml
Labels: Type: Bug, Priority: High, Status: Completed

#120 Release 1.6.4
  CHANGELOG.md
  openapi/openapi.yaml
Labels: Type: Maintenance, Priority: Low, Status: Completed
