Repository vrchatapi/specification, pull requests merged in 2022-11, with the labels that each got.

#189 Remove mentions of `showAvatar` and `hideAvatar`, and add note of them deprecated
  openapi/components/codeSamples/playermoderation.yaml
  openapi/components/paths/playermoderation.yaml
  openapi/components/schemas/PlayerModerationType.yaml
Labels: Type: Enhancement, Priority: Medium

#190 Release 1.9.0
  openapi/openapi.yaml
Labels: Priority: Low, Status: Blocked

#191 Removed friendRequestStatus from required user fields
  openapi/components/schemas/User.yaml
Labels: Type: Bug, Status: Review Needed

#192 Release 1.9.1
  openapi/openapi.yaml
Labels: Status: Blocked

#193 Notifications from the websocket have `receiverUserId` and do not have `seen`
  openapi/components/schemas/Notification.yaml
Labels: Type: Enhancement, Priority: Low
