Repository vrchatapi/specification, pull requests merged in 2022-12, with the labels that each got.

#201 Allow shortCode to be less than 6 characters
  openapi/components/schemas/GroupShortCode.yaml
Labels: Type: Bug

#203 Add optional roles[] to Group with ?includeRoles
  openapi/components/paths/groups.yaml
  openapi/components/schemas/Group.yaml
Labels: Type: Undocumented Endpoint

#204 Add title linting and fix resulting "title" errors
  .spectral.yaml
  functions/print.js
  functions/schema_object_name_mismatch_filename.js
  openapi/components/parameters.yaml
  openapi/components/paths/avatars.yaml
  openapi/components/paths/worlds.yaml
  openapi/components/schemas/APIConfig.yaml
  openapi/components/schemas/APIConfigAnnouncement.yaml
  openapi/components/schemas/APIConfigDownloadURLList.yaml
  openapi/components/schemas/APIConfigEvents.yaml
  openapi/components/schemas/FriendStatus.yaml
  openapi/components/schemas/GroupJoinState.yaml
  openapi/components/schemas/GroupPrivacy.yaml
  openapi/components/schemas/GroupRoleTemplate.yaml
  openapi/components/schemas/InfoPushData.yaml
  openapi/components/schemas/InfoPushDataArticle.yaml
  openapi/components/schemas/InfoPushDataArticleContent.yaml
  openapi/components/schemas/Instance.yaml
  openapi/components/schemas/InstancePlatforms.yaml
  openapi/components/schemas/OrderOption.yaml
  openapi/components/schemas/SortOption.yaml
  openapi/components/schemas/VerifyAuthTokenResult.yaml
  package-lock.json
Labels: Type: Maintenance

#205 Fix missing description linting in parameters.yaml
  openapi/components/parameters.yaml
Labels: Type: Maintenance

#208 Implement remaining Group API endpoints
  .spectral.yaml
  functions/print.js
  functions/schema_object_name_mismatch_filename.js
  openapi/components/parameters.yaml
  openapi/components/paths.yaml
  openapi/components/paths/files.yaml
  openapi/components/paths/groups.yaml
  openapi/components/requests/AddGroupGalleryImageRequest.yaml
  openapi/components/requests/BanGroupMemberRequest.yaml
  openapi/components/requests/CreateGroupAnnouncementRequest.yaml
  openapi/components/requests/CreateGroupGalleryRequest.yaml
  openapi/components/requests/CreateGroupRequest.yaml
  openapi/components/requests/RespondGroupJoinRequest.yaml
  openapi/components/requests/UpdateGroupGalleryRequest.yaml
  openapi/components/requests/UpdateGroupMemberRequest.yaml
  openapi/components/requests/UpdateGroupRequest.yaml
  openapi/components/responses/groups/DeleteGroupAnnouncementSuccess.yaml
  openapi/components/responses/groups/DeleteGroupGalleryImageSuccess.yaml
  openapi/components/responses/groups/DeleteGroupGallerySuccess.yaml
  openapi/components/responses/groups/GroupAlreadyMemberError.yaml
  openapi/components/responses/groups/GroupAnnouncementResponse.yaml
  openapi/components/responses/groups/GroupAuditLogListResponse.yaml
  openapi/components/responses/groups/GroupGalleryImageDeleteForbiddenError.yaml
  openapi/components/responses/groups/GroupGalleryImageListResponse.yaml
  openapi/components/responses/groups/GroupGalleryImageResponse.yaml
  openapi/components/responses/groups/GroupGalleryResponse.yaml
  openapi/components/responses/groups/GroupLimitedMemberResponse.yaml
  openapi/components/responses/groups/GroupPermissionListResponse.yaml
  openapi/components/responses/groups/GroupRoleIDListResponse.yaml
  openapi/components/schemas/Group.yaml
  openapi/components/schemas/GroupAnnouncement.yaml
  openapi/components/schemas/GroupAnnouncementID.yaml
  openapi/components/schemas/GroupAuditLogEntry.yaml
  openapi/components/schemas/GroupAuditLogID.yaml
  openapi/components/schemas/GroupGallery.yaml
  openapi/components/schemas/GroupGalleryImage.yaml
  openapi/components/schemas/GroupGalleryImageID.yaml
  openapi/components/schemas/GroupInviteAction.yaml
  openapi/components/schemas/GroupLimitedMember.yaml
  openapi/components/schemas/GroupMember.yaml
  openapi/components/schemas/GroupMemberLimitedUser.yaml
  openapi/components/schemas/GroupMemberStatus.yaml
  openapi/components/schemas/GroupPermission.yaml
  openapi/components/schemas/GroupRoleIDList.yaml
  openapi/components/schemas/GroupUserVisibility.yaml
  openapi/components/schemas/LimitedGroupMember.yaml
  openapi/components/schemas/PaginatedGroupAuditLogEntryList.yaml
Labels: Priority: Medium, Type: Undocumented Endpoint

#210 Add documentation deployment without SDK generation
  .github/workflows/ci.yaml
Labels: Type: Enhancement, Type: Maintenance, Priority: High

#211 Release 1.10.0
  .github/workflows/ci.yaml
  openapi/openapi.yaml
Labels: Priority: Medium

#215 Add accountDeletionLog to CurrentUser
  openapi/components/schemas/AccountDeletionLog.yaml
  openapi/components/schemas/CurrentUser.yaml
Labels: Type: Enhancement, Priority: Medium

#223 Fix GitHub CI
  .github/workflows/ci.yaml
Labels: Type: Maintenance, Priority: High

#222 Add "Verify Email Code" endpoint
  openapi/components/codeSamples/authentication.yaml
  openapi/components/paths.yaml
  openapi/components/paths/authentication.yaml
  openapi/components/requests/TwoFactorEmailCode.yaml
  openapi/components/responses/authentication/Verify2FAEmailCodeResponse.yaml
  openapi/components/schemas/Verify2FAEmailCodeResult.yaml
Labels: Priority: High, Type: Undocumented Endpoint
